# Generated by Django 3.2.17 on 2025-04-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_email_backend', '0003_auto_20220421_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Email Log', 'verbose_name_plural': 'Emails Log'},
        ),
        migrations.AlterField(
            model_name='email',
            name='bcc',
            field=models.TextField(blank=True, verbose_name='BCC'),
        ),
        migrations.AlterField(
            model_name='email',
            name='body',
            field=models.TextField(blank=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='email',
            name='cc',
            field=models.TextField(blank=True, verbose_name='CC'),
        ),
        migrations.AlterField(
            model_name='email',
            name='content_subtype',
            field=models.CharField(max_length=254, verbose_name='content subtype'),
        ),
        migrations.AlterField(
            model_name='email',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.CharField(blank=True, max_length=254, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='email',
            name='headers',
            field=models.TextField(blank=True, verbose_name='Headers'),
        ),
        migrations.AlterField(
            model_name='email',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.TextField(blank=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='email',
            name='to',
            field=models.TextField(blank=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='emailalternative',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['create_date'], name='db_email_ba_create__e261e8_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['from_email'], name='db_email_ba_from_em_237457_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['to'], name='db_email_ba_to_ccc278_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['cc'], name='db_email_ba_cc_f5ca2c_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['bcc'], name='db_email_ba_bcc_aa743c_idx'),
        ),
    ]
